name: Calculator

on:
  workflow_dispatch:
    inputs:
      num1:
        description: 'Enter the first number'
        required: true
      num2:
        description: 'Enter the second number'
        required: true
      operation:
        description: 'Enter the operation (+, -, *, or /)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run calculator program
        run: python calculator.py ${{ github.event.inputs.num1 }} ${{ github.event.inputs.num2 }} ${{ github.event.inputs.operation }}
