name: Calculator

on:
  workflow_dispatch:
    inputs:
      num1:
        description: 'Enter the first number'
        required: true
      num2:
        description: 'Enter the second number'
        required: true
      operation:
        description: 'Enter the operation '
        required: true
        type: choice
        options:
          - '+'
          - '-'
          - '*'
          - '/'
jobs:
  calculate:
    runs-on: ubuntu-latest
    outputs: 
      result: ${{ steps.calculate.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run calculator program
        run: |
          case "${{ steps.outputs.inputs.operation }}" in
            "+")
              result=$((${{ steps.inputs.outputs.num1 }} + ${{ steps.inputs.outputs.num2 }}))
              ;;
            "-")
              result=$((${{ steps.inputs.outputs.num1 }} - ${{ steps.inputs.outputs.num2 }}))
              ;;
            "*")
              result=$((${{ steps.inputs.outputs.num1 }} * ${{ steps.inputs.outputs.num2 }}))
              ;;
            "/")
              result=$((${{ steps.inputs.outputs.num1 }} / ${{ steps.inputs.outputs.num2 }}))
              ;;
            *)
              echo "Invalid operator" >&2
              exit 1
              ;;
          esac
          echo "::set-output name=result::$result"
          result: ${{ steps.calculate.outputs.result }}
  display:
    needs: [calculate]
    runs-on: ubuntu-latest
    steps:
      - name: Display result
        run: echo "Result:${{ needs.calculate.outputs.result}}"
    
          
          
          
          
          
          
          
