name: Calculator

on:
  workflow_dispatch:
    inputs:
      num1:
        description: 'Enter the first number'
        required: true
      num2:
        description: 'Enter the second number'
        required: true
      operator:
        description: 'Enter the operation '
        required: true
        default: ''
        type: choice
        options:
          - '+'
          - '-'
          - '*'
          - '/'
jobs:
  calculate_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run calculator
      id: calculate
      run: |
        num1=${{ github.event.inputs.num1 }}
        num2=${{ github.event.inputs.num2 }}
        operator=${{ github.event.inputs.operator }}

        if [ "$operator" = "+" ]; then
            result=$(expr $num1 + $num2)
        elif [ "$operator" = "-" ]; then
            result=$(expr $num1 - $num2)
        elif [ "$operator" = "*" ]; then
            result=$(expr $num1 * $num2)
        elif [ "$operator" = "/" ]; then
            result=$(expr $num1 / $num2)
        else
            echo "Invalid operator"
            exit 1
        fi
        echo "Result: $result"
  
  display_result_job:
    needs: calculate_job
    runs-on: ubuntu-latest
    steps:
    - name: Display result
      run: echo "Result is ${{ steps.calculate_job.id.result }}"
      
          
          
          
          
          
          
