name: Calculator

on:
  workflow_dispatch:
    inputs:
      number1:
        description: 'The first number'
        required: true
      number2:
        description: 'The second number'
        required: true
      operator:
        description: 'operator (+, -, *, /)'
        required: true

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run calculator
        run: |
          echo "Number 1: ${{ inputs.number1 }}"
          echo "Number 2: ${{ inputs.number2 }}"
          echo "Operator: ${{ inputs.operator }}"
          case $operator in
            1)RESULT='echo $number1 + $number2 | bc ';;
            2)RESULT='echo $number1 - $number2 | bc ';;
            3)RESULT='echo $number1 * $number2 | bc ';;
            4)RESULT='echo $number1 / $number2 | bc ';;
          esac
          echo "Result: $RESULT"
