name: Calculator Workflow

on:
  workflow_dispatch:
    inputs:
      num1:
        description: 'Enter first number'
        required: true
      num2:
        description: 'Enter second number'
        required: true
      operator:
        description: 'Enter operator (+,-,*,/)'
        type: choice
        options:
          - '+'
          - '-'
          - '*'
          - '/'

jobs:
  calculator_job:
    runs-on: ubuntu-latest
    steps:
    - name: Perform calculation
      run: |
        num1=$INPUT_NUM1
        num2=$INPUT_NUM2
        operator=$INPUT_OPERATOR
        result=0
        
        case $operator in
            '+')
                result=$(expr $num1 + $num2)
                ;;
            '-')
                result=$(expr $num1 - $num2)
                ;;
            '*')
                result=$(expr $num1 \* $num2)
                ;;
            '/')
                result=$(expr $num1 / $num2)
                ;;
            *)
                echo "Invalid operator entered"
                exit 1
                ;;
        esac
        
        echo "::set-output name=result::$result"
        
  display_result_job:
    needs: calculator_job
    runs-on: ubuntu-latest
    steps:
    - name: Display result
      run: |
        result=${{ needs.calculator_job.outputs.result }}
        echo "The result of the calculation is $result"
